### ISSUE TITLE
[Feature] 전투 시스템

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#1]
## ℹ Description

기본적인 전투 시스템 개발

## ✅ Tasks

- [x] 전투원 선택된 유저 클래스(CombatUser) 추가
- [x] 전투원별 무기 담당 클래스 추가 (Weapon) 
- [x] 전투원 선택 시 스킨 변경
- [x] 엔티티 인터페이스/클래스 (ICombatEntity, CombatEntity) 추가
- [x] 전투 메인 클래스 추가 (궁극기 상태, 스킬 상태 등 관리)
- [x] 전투원 스탯/스킬 인터페이스 추가 (IStats, ISkill)
- [x] 쿨타임을 별도의 인터페이스로 관리 (HasCooldown)

## 💬 Comment
--
