### ISSUE TITLE
무기 및 스킬 설명창 개편

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#103]
## ℹ Description
전투원의 무기 및 스킬 설명창 개편

## ✅ Tasks
- [x] 설명 아이콘 개편
- [x] 무기 및 스킬 설명 개편
- [x] 누락된 설명 표기 (전투원 '아케이스' 제외 모두)

## 💬 Comment
UI/디자인 요소이므로 우선 순위는 낮음.
