### ISSUE TITLE
전투원 '니스' 추가

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#146]
## ℹ Description
전투원 '니스' 추가

## ✅ Tasks
- [x] 전투원 클래스 추가
- [x] 기본무기 구현
- [x] 패시브 1번스킬 구현
- [x] 액티브 1번스킬 구현
- [x] 액티브 2번스킬 구현
- [x] 액티브 3번스킬 구현
- [x] 궁극기 구현
- [x] 더미 엔티티 팀 식별자 변경 기능 추가 (아군 테스트용)

## 💬 Comment
--
