### ISSUE TITLE
[Feature] 전체 코드 리팩토링

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#18]
## ℹ Description
원활한 유지보수를 위한 전체 리팩토링

## ✅ Tasks
- [x] 이벤트 구조 개편
- [x] EntityList 클래스 개편
- [x] 전투 관련 코드 개편
- [x] 패키지 정리

## 💬 Comment
--
