### ISSUE TITLE
전투원 

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#186]
## ℹ Description
전투원 '(이름)' 추가

## ✅ Tasks
- [ ] 전투원 클래스 추가
- [ ] 기본무기 구현
- [ ] 액티브 1번스킬 구현
- [ ] 액티브 2번스킬 구현
- [ ] 액티브 3번스킬 구현
- [ ] 궁극기 구현

## 💬 Comment
기타 할 말
