### ISSUE TITLE
[Feature] 투사체 세부 시스템 추가

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#38]
## ℹ Description
투사체(Projectile) 중력 및 도탄 시스템 추가

## ✅ Tasks
- [x] 투사체 세부 속성 및 빌더 추가
- [x] 투사체 중력 여부 추가
- [x] 투사체 도탄 여부 추가

## 💬 Comment
--
