### ISSUE TITLE
[Feature] 전투 시스템 - II

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#7]
## ℹ Description

구체적으로 전투 시스템 구현

## ✅ Tasks

- [x] TemporalEntity를 상속받는 실험용 더미 엔티티(Dummy) 추가
- [x] 데미지 시스템 구현
- [x] 킬/리스폰 시스템 구현
- [x] 이동속도 시스템 구현

## 💬 Comment
테스트용 코드(더미 소환 등)는 커밋 금지
