### ISSUE TITLE
전투원 '예거' 추가

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#83]
## ℹ Description
전투원 '예거' 추가

## ✅ Tasks
- [x] 전투원 클래스 추가
- [x] 전투원 스탯/스킬 클래스 추가
- [x] 특성 구현
- [x] 패시브 1번스킬 구현
- [x] 1번스킬 구현
- [x] 2번스킬 구현
- [x] 3번스킬 구현
- [x] 궁극기 구현

## 💬 Comment
기타 할 말
