### ISSUE TITLE
히트박스 시스템 수정

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#90]
## ℹ Description
히트박스 판정 시스템의 고도화 및 리팩토링

## ✅ Tasks
- [x] 엔티티가 여러 히트박스를 가질 수 있도록 수정
- [x] HasCritHitbox 인터페이스로 치명타가 가능한 엔티티 지정
- [x] 판정 알고리즘 수정

## 💬 Comment
--
